[package]
name = "blockchain"
version = "0.1.0"
authors = ["zenoxygen <zenoxygen@protonmail.com>"]
edition = "2018"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.4.0"
crypto-hash = "0.3.4"
